### ISSUE TITLE
will you open the code of your article?

### ISSUE THREAD

**Issue by jchen106** [sharmasushil/Navigating-Uncertainty-Trajectory-Prediction#1]

**Comment by sharmasushil** [comment]
Hi, 

I will open code soon, but I am using same concept for Graph Neural network with LSTM. It will update soon

**Comment by jchen106** [comment]
hi,thank you for your reply,looking forward to see how cnn-lstm work

**Comment by sharmasushil** [comment]
Hi, Let me finish my GNN-LSTM model, I will update you soon. Keep eye on this repo. 
Thanks 

Have a good day
