### ISSUE TITLE
Can you tell me how to collect trajectory data in carla? Is there any relevant code in carla? thank you.

### ISSUE THREAD

**Issue by jchen106** [sharmasushil/Navigating-Uncertainty-Trajectory-Prediction#2]
how to collect trajectory data in carla

**Comment by sharmasushil** [comment]
you could use the GNSS sensor, this simulates lattitude and longitude as given by a GPS sensor. But if you want raw coordinates, you can also directly use the vehicle's transform, this isn't a sensor it's just a property of the vehicle you can access through the get_transform() method of an actor. 

Line of code:
x, y, z = vehicle.get_transform().location.x, ​

          vehicle.get_transform().location.y,​

          vehicle.get_transform().location.z​


Let me know if you are able to get the trajectory data. Note that above code line only for ego vehicle.
