### ISSUE TITLE
Where is your evaluation code?

### ISSUE THREAD

**Issue by Ezharjan** [sharmasushil/Navigating-Uncertainty-Trajectory-Prediction#3]

**Comment by sharmasushil** [comment]
Hello,
Thank you for reaching out with your query.

Currently, we're engaged in developing same concept using another model , and we aim to release our code shortly. This work under the company policy so we share method code one 
.
Feel free to explore and utilise our shared dataset as part of your work.

Kind regards,
Sushil

**Comment by sharmasushil** [comment]
Let me if you have more question
